102 ssl on services
erigones/esdc-factory pull request #104
Opened 2017-12-17 10:17 UTC by YanChii

Related to #102

2017-12-17 10:18 UTC, YanChii commented
Patches to `computenode.sh` are waiting for cfgdb REST service.

2018-01-02 16:31 UTC, dn0 requested changes
We are on the right track here. Please document the new metadata in docs/appliances.rst.

We should make a decision about the upgrade path. Whether the new ZK Rest service will be deployed on an old cfgdb during the mgmt upgrade:
    * If no, then we have to use `query_cfgdb --old` when connecting to  2181. 
    * If yes, then we should only allow query_cfgdb connections to 12181. And we have to decide what to do about the SSL certificate on cfgdb (I suggest that we create one during the upgrade).

There are only small changes needed in regards to the new query_cfgdb (https://github.com/erigones/esdc-ce/pull/335).

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	"${TIMEOUT}" "${waittime}" nc -z "${host}" "${port}"
Why timeout instead of `nc -w`?

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +			if
There should not be a newline after `if`. Overall, this if statement is hard to read.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +set -e
`set -o errexit` is already there.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	if [[ -z "${svc_cert}" && "${CONFIG_remote_node}" -eq 1 ]]; then
This `if` can be written in a more readable way. The `${CONFIG_remote_node}` check should be nested inside the `-z "${svc_cert}"` if.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	ln -s "../$(basename "${SVC_CERT_FILE}")" "certs/$("${OPENSSL}" x509 -hash -noout -in "${SVC_CERT_FILE}").0"
This won't work. The CWD is unclear at this point.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/headnode.sh.j2
> +		fatal "Unable to query cfgdb."
Most fatal errors don't have a dot at the end of the sentence.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +				test_port_open "${CFGDB_IP}" "{{ esdc_cfgdb.zookeeper.port_ssl }}" ||
We should also use this test to further distinguish between new-style and old-style querying of cfgdb. The new `query_cfgdb` will automatically connect via http(s) to 12181. It requires a `--old` or `--legacy` switch in order to use the old `zookeepercli` way of connecting to cfgdb port 2181.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +		fatal "Unable to query cfgdb."
Most fatal errors don't have a dot at the end of the sentence.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	"${QUERY_CFGDB}" ${cmd}
Rather use `"${@}"` here and don't store it in a non-array variable.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +				test_port_open "${CFGDB_IP}" "{{ esdc_cfgdb.zookeeper.port_ssl }}" ||
Or we should consider dropping support for adding new compute nodes to pre-3.0 management.

2018-01-02 16:31 UTC, dn0 commented on ansible/roles/esdc-mgmt/templates/haproxy/haproxy.cfg.j2
> +	server zookeeper-cfgdb %CFGDB_IP%:{{ esdc_cfgdb.zookeeper.port }}
This will break the haproxy and testing during the build phase.

I suggest that this is 127:0.0.1:<zk_port> by default and the sed command should replace this pattern in es-post-deploy.sh.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/headnode.sh.j2
> +	if [[ -z "$(_zk get /esdc)" ]]; then
Querying the top-level /esdc is forbidden in our new ZK rest service, e.g. query /esdc/settings.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	if [[ -z "$(_zk get /esdc)" ]]; then
Querying the top-level /esdc is forbidden in our new ZK rest service, e.g. query /esdc/settings.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/headnode.sh.j2
> +	ln -s "../$(basename "${SVC_CERT_FILE}")" "certs/$("${OPENSSL}" x509 -hash -noout -in "${SVC_CERT_FILE}").0"
I'm not sure where this symlink will land.

2018-01-02 16:31 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	_zk_noerror rmr --force "/esdc/nodes/hosts/${SYSINFO_UUID}"
Yes, this will work with the new query_cfgdb.

2018-01-02 16:31 UTC, dn0 commented on ansible/roles/esdc-mgmt/templates/esdc/es-post-deploy.sh.j2
> +sed -i'' -e "s/%CFGDB_IP%/${CFGDB_IP}/g" /etc/haproxy/haproxy.cfg
Please see comment haproxy.cfg.j2. We can change this so it is replaced only if the cfgdb_ip metadata is found but the search pattern will be different.

2018-01-06 08:13 UTC, dn0 requested changes

2018-01-06 08:13 UTC, dn0 commented on ansible/templates/usb/zones/esdc-cfgdb.vmmanifest.j2
> +    "org.erigones:erigonesd_ssl_cert": "@ERIGONESD_SSL_CERT@",
The metadata name will be different. Please see #108.
I suggest that we unify the metadata in a way that both mgmt and cfgdb have a separate mdata for the key and cert:

* mgmt:
   * org.erigones:erigonesd_ssl_cert
   * org.erigones:erigonesd_ssl_key

* cfgdb (#108)
   * org.erigones:cfgdb_zk_rest_ssl_cer
   * rg.erigones:cfgdb_zk_rest_ssl_key

2018-01-06 08:13 UTC, dn0 commented on ansible/templates/usb/scripts/headnode.sh.j2
> +	SVC_CERT_COMBINED_B64="$(cat "${svc_key_tmpfile}" "${svc_cert_tmpfile}" | "${BASE64}" -w 0)"
Please consider not combining the SSL certificate. Lets keep the certificate and key in separate variables a pass it to the services like that. The service should decide where and how to store the certificate. Also the base64 is not needed and we should not use it (the certificate/key is already in pem format). Newlines in json/metadata is not a problem.

2018-01-06 08:55 UTC, dn0 requested changes

2018-01-06 08:55 UTC, dn0 commented on ansible/templates/usb/scripts/computenode.sh.j2
> +SVC_CERT_FILE="${OPENSSL_HOME}/dc-erigonesd.pem"
We should not save the certificate into /opt/local on the compute node. Lets use /opt/custom/etc for this.

2018-01-06 15:24 UTC, dn0 requested changes

2018-01-06 15:24 UTC, dn0 commented on ansible/roles/esdc-mgmt/templates/haproxy/haproxy.cfg.j2
> +	server zookeeper-cfgdb %CFGDB_IP%:{{ esdc_cfgdb.zookeeper.port }}
The new haproxy configuration should like like this - see https://github.com/erigones/esdc-ce/compare/v2.7...102_ssl_on_services?expand=1#diff-98cb9577198e29577172ad5c2efc489cR16

```
# BEGIN Danube Cloud rabbitmq service proxy
listen rabbitmq
        mode tcp
        bind *:15672 ssl crt /etc/pki/tls/certs/dc-erigonesd.pem
        server rabbitmq-mgmt 127.0.0.1:5672
# END Danube Cloud rabbitmq service proxy

# BEGIN Danube Cloud redis service proxy
listen redis
        mode tcp
        bind *:16379 ssl crt /etc/pki/tls/certs/dc-erigonesd.pem
        server redis-mgmt 127.0.0.1:6379
# END Danube Cloud redis service proxy

# BEGIN Danube Cloud zk_rest service proxy
listen zk_rest
        mode tcp
        bind *:12181
        server zk-rest-cfgdb 10.0.60.165:12181
# END Danube Cloud zk_rest service proxy
```

2018-01-10 23:04 UTC, YanChii commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	"${TIMEOUT}" "${waittime}" nc -z "${host}" "${port}"
`-w` affects only open connections, not connect timeouts

2018-01-10 23:09 UTC, YanChii commented on ansible/templates/usb/scripts/computenode.sh.j2
> +	if [[ -z "${svc_cert}" && "${CONFIG_remote_node}" -eq 1 ]]; then
After last discussion, we won't support non-SSL fallback. Therefore remote node does not differ from a normal node and this condition is not needed.
As a consequence, it won't be possible to connect v3.0.0+ node to pre-v3.0.0 mgmt.

2018-01-11 13:11 UTC, dn0 approved these changes

2018-01-11 13:11 UTC, merged