add zookeepercli and query_cfgdb to cfgdb VM
erigones/esdc-factory pull request #51
Opened 2017-06-05 15:08 UTC by YanChii

CFGDB update to resolve #50

2017-06-05 19:32 UTC, dn0 requested changes

2017-06-05 19:32 UTC, dn0 commented on ansible/roles/esdc-cfgdb/files/query_cfgdb
> +exit $?
Does this return the exit code of the `"${ZKCLI}"` command or of the `if` statement?

2017-06-05 19:32 UTC, dn0 commented on ansible/roles/esdc-cfgdb/files/query_cfgdb
> +if [ -z "${QUERY_STRING}" ]; then
Lets use double brackets everywhere

2017-06-06 07:33 UTC, YanChii commented on ansible/roles/esdc-cfgdb/files/query_cfgdb
> +exit $?
```
janci@nb:~$ if true; then ls aaa; else echo bbb; fi
ls: cannot access 'aaa': No such file or directory
janci@nb:~$ echo $?
2
janci@nb:~$ if false; then ls aaa; else echo bbb; fi
bbb
janci@nb:~$ echo $?
0
```

2017-06-06 07:38 UTC, dn0 approved these changes

2017-06-06 07:43 UTC, merged