Add access zone image
erigones/esdc-factory pull request #63
Opened 2017-07-14 15:45 UTC by YanChii

Not very featureful so far.. but serves the main purpose - create a NAT zone for any subnet in one click.

2017-07-26 16:42 UTC, dn0 commented on ansible/build-access-zone.yml
> +    image_tags: {internal: true, resize: true, deploy: false}
internal=false

2017-07-26 16:42 UTC, dn0 commented on ansible/vars/build/vm/access-zone.yml
> +zone_nic_0_ip: "{{ build_ips.esdc_dns | default(build_ip) }}"
~~esdc_dns~~

2017-08-08 05:41 UTC, dn0 requested changes

2017-08-08 05:41 UTC, dn0 commented on docs/network/access-zone.rst
> +The image supports following metadata:
Please add information (link to) that it is based on base-64-es.

2017-08-08 05:41 UTC, dn0 commented on docs/network/access-zone.rst
> +2.6.1
Are we going to use this version scheme, or dates?

2017-08-08 05:41 UTC, dn0 commented on docs/network/access-zone.rst
> +* **cloud-init** modules: growpart, resizefs, ssh, set-passwords.
No cloud-init here.

2017-08-08 05:41 UTC, dn0 commented on docs/network/access-zone.rst
> +In order to use it, you should create a VM in a following way:
VM -> SunOS Zone (thats the OS type)

2017-08-10 11:26 UTC, YanChii commented
Is it ok to merge now?

2017-08-10 11:35 UTC, dn0 requested changes

2017-08-10 11:35 UTC, dn0 commented on ansible/vars/build/vm/network-access-zone.yml
> +zone_uuid: 4cb74eb8-8f37-4a0d-aa37-7d8f50083970
Please change this uuid to something unique.

2017-08-10 12:58 UTC, YanChii commented on ansible/vars/build/vm/network-access-zone.yml
> +zone_uuid: 4cb74eb8-8f37-4a0d-aa37-7d8f50083970
Done.

2017-08-10 13:41 UTC, dn0 approved these changes

2017-08-10 22:44 UTC, merged