include discover_cfgdb() in cn install
erigones/esdc-factory pull request #67
Opened 2017-08-15 12:01 UTC by YanChii

Broken cn install (prints error during cfgdb discovery). The source of the problem is incorrect templating of prompt-config.sh. The function discover_cfgdb() is incorrectly included only in first node install.

2017-08-15 12:07 UTC, dn0 approved these changes

2017-08-15 12:08 UTC, dn0 requested changes
Missing changelog in usb.rst

2017-08-19 10:44 UTC, YanChii commented
The next problem is lack of python interpreter in the platform. Rewritten cfgdb_discovery code to C.

2017-08-21 09:09 UTC, dn0 requested changes

2017-08-21 09:09 UTC, dn0 commented on ansible/files/sources/cfgdb_discovery.c
> +    return 0;
The former python version returned with exit code 0 only when a CFGDB IP address was found (the same goes for line 93)

2017-08-21 10:04 UTC, dn0 approved these changes

2017-08-21 10:04 UTC, merged