Fix prompt-config.sh when admin network is on dhcp
erigones/esdc-factory pull request #70
Opened 2017-08-18 11:44 UTC by YanChii

Conversation in erigones/esdc-ce#240

2017-10-11 09:13 UTC, YanChii commented
Pushed a (hopefully) final change for this PR. Should run fine but testing needed before release.

2017-10-14 18:05 UTC, dn0 requested changes

2017-10-14 18:05 UTC, dn0 commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +		if [ "${admin_ip}" == "dhcp" ]; then
We always use double brackets `[[`.

2017-10-14 18:05 UTC, dn0 commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +			echo "The first node cannot have a dynamic admin address during install."
We should clear the `$admin_ip` variable in this case (`admin_ip=""`).
Sentence update:
- *node* -> *compute node*
- *address* -> *IP address*

2017-10-16 13:25 UTC, dn0 approved these changes

2017-10-17 08:49 UTC, merged