Added support for admin NIC tag on etherstub + ability to change MAC addresses of physical interfaces
erigones/esdc-factory pull request #87
Opened 2017-10-28 20:15 UTC by dn0

Issue #78 and #86

2017-11-14 14:22 UTC, YanChii requested changes

2017-11-14 14:22 UTC, YanChii commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +	local re='^[a-zA-Z0-9_]*[0-9]$'
Is e.g. `1234` a valid stub name? 
If not, I recommend changing regex to `^[a-zA-Z0-9_]+[0-9]+$` or better `^[a-zA-Z0-9_]*[a-zA-Z_][0-9]+$`

2017-11-14 14:22 UTC, YanChii commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +{% raw %}
Why this is needed here?

2017-11-14 14:22 UTC, YanChii commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +					fi
We should consider setting this by default without prompting the user. It may seem scary but actually I can't find a drawback of this decision.

2017-11-14 15:09 UTC, dn0 commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +{% raw %}
Because `{#` below will be interpreted as a jinja2 comment.

2017-11-14 15:10 UTC, dn0 commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +	local re='^[a-zA-Z0-9_]*[0-9]$'
Taken from https://github.com/erigones/smartos-live/blob/master/src/nictagadm#L162

2017-11-14 15:12 UTC, dn0 commented on ansible/templates/usb/scripts/prompt-config.sh.j2
> +					fi
I understand, but I would rather change the default to "yes" and keep the question here.

2017-11-15 14:44 UTC, YanChii approved these changes

2017-11-15 14:45 UTC, merged